spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: ${DB_URL}
    password: ${DB_USERNAME}
    username: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 8081